#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Bittrex\Application\KernelApplication;
use Bittrex\Command\TerminalCommand;
use Bittrex\Term\WalletShowCommand;

$command = new TerminalCommand();
$application = new KernelApplication();
$application->add($command);
$application->setDefaultCommand($command->getName());
$application->add(new WalletShowCommand());
$application->run();
