#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Bittrex\Application\KernelApplication;
use Bittrex\Command\TerminalCommand;
use Bittrex\Command\SetupCommand;

$command = new TerminalCommand();
$application = new KernelApplication();
$application->add($command);
$application->setDefaultCommand($command->getName());

foreach (TerminalCommand::commandRegistry() as $command) {
  $application->add(new $command());
}
$application->add(new SetupCommand());
$application->run();
